# Generated by Django 5.0 on 2024-10-25 03:56

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=service.models.caminho_imagem),
        ),
    ]
