# Generated by Django 5.0 on 2024-10-25 08:08

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('content', models.TextField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=service.models.caminho_imagem)),
            ],
        ),
    ]
