# Generated by Django 5.0 on 2024-10-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
