# Generated by Django 5.0 on 2024-10-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
