# Generated by Django 5.0 on 2024-10-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_title_event_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='nome',
            new_name='name',
        ),
    ]
